name: sar_safe_route_finder
description: SAR Safe Route Finder - Flutter frontend
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.6.1
  permission_handler: ^11.3.1
  geolocator: ^10.1.0


  http: ^0.13.5
  web_socket_channel: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
